### ISSUE TITLE
USER STORY : Footer

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/Celtic-Tiles#39]
As a **Developer User** I can **create a footer** so that I can **add social links and site information for the user**
  
  
## Acceptance Criteria
*Add footer link  in base.html 

# Tasks
- [x] create a html file in includes folder
- [x] create css and add to base css
- [x] add pricay ploicy
- [x] add subscribe from mailchimp
- [x] add social links
- [x] add adrress and opening times
- [x] add contact us link 
- [x] add blog link
